[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "satoverpass"
version = "0.1.0"
description = "Predict satellite overpass times using TLE data"
authors = [{ name="Upendra Oli", email="upendra.oli59@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
dependencies = [
    "skyfield",
    "numpy",
    "pandas",
    "requests"
]

[project.urls]
Homepage = "https://github.com/yourusername/satoverpass"
